const deck = {
  twoC: {
    name: "Two of Clubs",
    suit: "clubs",
    color: "black",
    value: "2",
    img: "static/2_of_clubs.png",
  },
  twoD: {
    name: "Two of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "2",
    img: "static/2_of_diamonds.png",
  },
  twoH: {
    name: "Two of Hearts",
    suit: "hearts",
    color: "red",
    value: "2",
    img: "static/2_of_hearts.png",
  },
  twoS: {
    name: "Two of Spades",
    suit: "spades",
    color: "black",
    value: "2",
    img: "static/2_of_spades.png",
  },
  threeC: {
    name: "Three of Clubs",
    suit: "clubs",
    color: "black",
    value: "3",
    img: "static/3_of_clubs.png",
  },
  threeD: {
    name: "Three of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "3",
    img: "static/3_of_diamonds.png",
  },
  threeH: {
    name: "Three of Hearts",
    suit: "hearts",
    color: "red",
    value: "3",
    img: "static/3_of_hearts.png",
  },
  threeS: {
    name: "Three of Spades",
    suit: "spades",
    color: "black",
    value: "3",
    img: "static/3_of_spades.png",
  },
  fourC: {
    name: "Four of Clubs",
    suit: "clubs",
    color: "black",
    value: "4",
    img: "static/4_of_clubs.png",
  },
  fourD: {
    name: "Four of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "4",
    img: "static/4_of_diamonds.png",
  },
  fourH: {
    name: "Four of Hearts",
    suit: "hearts",
    color: "red",
    value: "4",
    img: "static/4_of_hearts.png",
  },
  fourS: {
    name: "Four of Spades",
    suit: "spades",
    color: "black",
    value: "4",
    img: "static/4_of_spades.png",
  },
  fiveC: {
    name: "Five of Clubs",
    suit: "clubs",
    color: "black",
    value: "5",
    img: "static/5_of_clubs.png",
  },
  fiveD: {
    name: "Five of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "5",
    img: "static/5_of_diamonds.png",
  },
  fiveH: {
    name: "Five of Hearts",
    suit: "hearts",
    color: "red",
    value: "5",
    img: "static/5_of_hearts.png",
  },
  fiveS: {
    name: "Five of Spades",
    suit: "spades",
    color: "black",
    value: "5",
    img: "static/5_of_spades.png",
  },
  sixC: {
    name: "Six of Clubs",
    suit: "clubs",
    color: "black",
    value: "6",
    img: "static/6_of_clubs.png",
  },
  sixD: {
    name: "Six of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "6",
    img: "static/6_of_diamonds.png",
  },
  sixH: {
    name: "Six of Hearts",
    suit: "hearts",
    color: "red",
    value: "6",
    img: "static/6_of_hearts.png",
  },
  sixS: {
    name: "Six of Spades",
    suit: "spades",
    color: "black",
    value: "6",
    img: "static/6_of_spades.png",
  },
  sevenC: {
    name: "Seven of Clubs",
    suit: "clubs",
    color: "black",
    value: "7",
    img: "static/7_of_clubs.png",
  },
  sevenD: {
    name: "Seven of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "7",
    img: "static/7_of_diamonds.png",
  },
  sevenH: {
    name: "Seven of Hearts",
    suit: "hearts",
    color: "red",
    value: "7",
    img: "static/7_of_hearts.png",
  },
  sevenS: {
    name: "Seven of Spades",
    suit: "spades",
    color: "black",
    value: "7",
    img: "static/7_of_spades.png",
  },
  eightC: {
    name: "Eight of Clubs",
    suit: "clubs",
    color: "black",
    value: "8",
    img: "static/8_of_clubs.png",
  },
  eightD: {
    name: "Eight of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "8",
    img: "static/8_of_diamonds.png",
  },
  eightH: {
    name: "Eight of Hearts",
    suit: "hearts",
    color: "red",
    value: "8",
    img: "static/8_of_hearts.png",
  },
  eightS: {
    name: "Eight of Spades",
    suit: "spades",
    color: "black",
    value: "8",
    img: "static/8_of_spades.png",
  },
  nineC: {
    name: "Nine of Clubs",
    suit: "clubs",
    color: "black",
    value: "9",
    img: "static/9_of_clubs.png",
  },
  nineD: {
    name: "Nine of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "9",
    img: "static/9_of_diamonds.png",
  },
  nineH: {
    name: "Nine of Hearts",
    suit: "hearts",
    color: "red",
    value: "9",
    img: "static/9_of_hearts.png",
  },
  nineS: {
    name: "Nine of Spades",
    suit: "spades",
    color: "black",
    value: "9",
    img: "static/9_of_spades.png",
  },
  tenC: {
    name: "Ten of Clubs",
    suit: "clubs",
    color: "black",
    value: "10",
    img: "static/10_of_clubs.png",
  },
  tenD: {
    name: "Ten of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "10",
    img: "static/10_of_diamonds.png",
  },
  tenH: {
    name: "Ten of Hearts",
    suit: "hearts",
    color: "red",
    value: "10",
    img: "static/10_of_hearts.png",
  },
  tenS: {
    name: "Ten of Spades",
    suit: "spades",
    color: "black",
    value: "10",
    img: "static/10_of_spades.png",
  },
  jackC: {
    name: "Jack of Clubs",
    suit: "clubs",
    color: "black",
    value: "J",
    img: "static/jack_of_clubs.png",
  },
  jackD: {
    name: "Jack of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "J",
    img: "static/jack_of_diamonds.png",
  },
  jackH: {
    name: "Jack of Hearts",
    suit: "hearts",
    color: "red",
    value: "J",
    img: "static/jack_of_hearts.png",
  },
  jackS: {
    name: "Jack of Spades",
    suit: "spades",
    color: "black",
    value: "J",
    img: "static/jack_of_spades.png",
  },
  queenC: {
    name: "Queen of Clubs",
    suit: "clubs",
    color: "black",
    value: "Q",
    img: "static/queen_of_clubs.png",
  },
  queenD: {
    name: "Queen of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "Q",
    img: "static/queen_of_diamonds.png",
  },
  queenH: {
    name: "Queen of Hearts",
    suit: "hearts",
    color: "red",
    value: "Q",
    img: "static/queen_of_hearts.png",
  },
  queenS: {
    name: "Queen of Spades",
    suit: "spades",
    color: "black",
    value: "Q",
    img: "static/queen_of_spades.png",
  },
  kingC: {
    name: "King of Clubs",
    suit: "clubs",
    color: "black",
    value: "K",
    img: "static/king_of_clubs.png",
  },
  kingD: {
    name: "King of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "K",
    img: "static/king_of_diamonds.png",
  },
  kingH: {
    name: "King of Hearts",
    suit: "hearts",
    color: "red",
    value: "K",
    img: "static/king_of_hearts.png",
  },
  kingS: {
    name: "King of Spades",
    suit: "spades",
    color: "black",
    value: "K",
    img: "static/king_of_spades.png",
  },
  aceC: {
    name: "Ace of Clubs",
    suit: "clubs",
    color: "black",
    value: "A",
    img: "static/ace_of_clubs.png",
  },
  aceD: {
    name: "Ace of Diamonds",
    suit: "diamonds",
    color: "red",
    value: "A",
    img: "static/ace_of_diamonds.png",
  },
  aceH: {
    name: "Ace of Hearts",
    suit: "hearts",
    color: "red",
    value: "A",
    img: "static/ace_of_hearts.png",
  },
  aceS: {
    name: "Ace of Spades",
    suit: "spades",
    color: "black",
    value: "A",
    img: "static/ace_of_spades.png",
  },
};

console.log(deck.aceS);
