const deck = {
  clubs: [
    {
      twoOfClubs: {
        name: "Two of Clubs",
        suit: "clubs",
        color: "black",
        value: "2",
        deckNumber: 1,
        img: "static/2_of_clubs.png",
      },
      threeOfClubs: {
        name: "Three of Clubs",
        suit: "clubs",
        color: "black",
        value: "3",
        deckNumber: 2,
        img: "static/3_of_clubs.png",
      },
      fourofClubs: {
        name: "Four of Clubs",
        suit: "clubs",
        color: "black",
        value: "4",
        deckNumber: 3,
        img: "static/4_of_clubs.png",
      },
      fiveOfClubs: {
        name: "Five of Clubs",
        suit: "clubs",
        color: "black",
        value: "5",
        deckNumber: 4,
        img: "static/5_of_clubs.png",
      },
      sixOfClubs: {
        name: "Six of Clubs",
        suit: "clubs",
        color: "black",
        value: "6",
        deckNumber: 5,
        img: "static/6_of_clubs.png",
      },
      sevenOfClubs: {
        name: "Seven of Clubs",
        suit: "clubs",
        color: "black",
        value: "7",
        deckNumber: 6,
        img: "static/7_of_clubs.png",
      },
      eightOfClubs: {
        name: "Eight of Clubs",
        suit: "clubs",
        color: "black",
        value: "8",
        deckNumber: 7,
        img: "static/8_of_clubs.png",
      },
      nineOfClubs: {
        name: "Nine of Clubs",
        suit: "clubs",
        color: "black",
        value: "9",
        deckNumber: 6,
        img: "static/9_of_clubs.png",
      },
      tenOfClubs: {
        name: "Ten of Clubs",
        suit: "clubs",
        color: "black",
        value: "10",
        deckNumber: 9,
        img: "static/10_of_clubs.png",
      },
      jackOfClubs: {
        name: "Jack of Clubs",
        suit: "clubs",
        color: "black",
        value: "J",
        deckNumber: 10,
        img: "static/jack_of_clubs.png",
      },
      queenOfClubs: {
        name: "Queen of Clubs",
        suit: "clubs",
        color: "black",
        value: "Q",
        deckNumber: 11,
        img: "static/queen_of_clubs.png",
      },
      kingOfClubs: {
        name: "King of Clubs",
        suit: "clubs",
        color: "black",
        value: "K",
        deckNumber: 12,
        img: "static/king_of_clubs.png",
      },
      aceOfClubs: {
        name: "Ace of Clubs",
        suit: "clubs",
        color: "black",
        value: "A",
        deckNumber: 13,
        img: "static/ace_of_clubs.png",
      },
    },
  ],
  diamonds: [
    {
      twoOfDiamonds: {
        name: "Two of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "2",
        deckNumber: 14,
        img: "static/2_of_diamonds.png",
      },
      threeOfDiamonds: {
        name: "Three of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "3",
        deckNumber: 15,
        img: "static/3_of_diamonds.png",
      },
      fourOfDiamonds: {
        name: "Four of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "4",
        deckNumber: 16,
        img: "static/4_of_diamonds.png",
      },
      fiveOfDiamonds: {
        name: "Five of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "5",
        deckNumber: 17,
        img: "static/5_of_diamonds.png",
      },
      sixOfDiamonds: {
        name: "Six of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "6",
        deckNumber: 18,
        img: "static/6_of_diamonds.png",
      },
      sevenOfDiamonds: {
        name: "Seven of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "7",
        deckNumber: 19,
        img: "static/7_of_diamonds.png",
      },
      eightOfDiamonds: {
        name: "Eight of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "8",
        deckNumber: 20,
        img: "static/8_of_diamonds.png",
      },
      nineOfDiamonds: {
        name: "Nine of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "9",
        deckNumber: 21,
        img: "static/9_of_diamonds.png",
      },
      tenOfDiamonds: {
        name: "Ten of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "10",
        deckNumber: 22,
        img: "static/10_of_diamonds.png",
      },
      jackOfDiamonds: {
        name: "Jack of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "J",
        deckNumber: 23,
        img: "static/jack_of_diamonds.png",
      },
      queenOfDiamonds: {
        name: "Queen of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "Q",
        deckNumber: 24,
        img: "static/queen_of_diamonds.png",
      },
      kingOfDiamonds: {
        name: "King of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "K",
        deckNumber: 25,
        img: "static/king_of_diamonds.png",
      },
      aceOfDiamonds: {
        name: "Ace of Diamonds",
        suit: "diamonds",
        color: "red",
        value: "A",
        deckNumber: 26,
        img: "static/ace_of_diamonds.png",
      },
    },
  ],
  hearts: [
    {
      twoOfHearts: {
        name: "Two of Hearts",
        suit: "hearts",
        color: "red",
        value: "2",
        deckNumber: 27,
        img: "static/2_of_hearts.png",
      },
      threeOfHearts: {
        name: "Three of Hearts",
        suit: "hearts",
        color: "red",
        value: "3",
        deckNumber: 28,
        img: "static/3_of_hearts.png",
      },
      fourOfHearts: {
        name: "Four of Hearts",
        suit: "hearts",
        color: "red",
        value: "4",
        deckNumber: 29,
        img: "static/4_of_hearts.png",
      },
      fiveOfHearts: {
        name: "Five of Hearts",
        suit: "hearts",
        color: "red",
        value: "5",
        deckNumber: 30,
        img: "static/5_of_hearts.png",
      },
      sixOfHearts: {
        name: "Six of Hearts",
        suit: "hearts",
        color: "red",
        value: "6",
        deckNumber: 31,
        img: "static/6_of_hearts.png",
      },
      sevenOfHearts: {
        name: "Seven of Hearts",
        suit: "hearts",
        color: "red",
        value: "7",
        deckNumber: 32,
        img: "static/7_of_hearts.png",
      },
      eightOfHearts: {
        name: "Eight of Hearts",
        suit: "hearts",
        color: "red",
        value: "8",
        deckNumber: 33,
        img: "static/8_of_hearts.png",
      },
      nineOfHearts: {
        name: "Nine of Hearts",
        suit: "hearts",
        color: "red",
        value: "9",
        deckNumber: 34,
        img: "static/9_of_hearts.png",
      },
      tenOfHearts: {
        name: "Ten of Hearts",
        suit: "hearts",
        color: "red",
        value: "10",
        deckNumber: 35,
        img: "static/10_of_hearts.png",
      },
      jackOfHearts: {
        name: "Jack of Hearts",
        suit: "hearts",
        color: "red",
        value: "J",
        deckNumber: 36,
        img: "static/jack_of_hearts.png",
      },
      queenOfHearts: {
        name: "Queen of Hearts",
        suit: "hearts",
        color: "red",
        value: "Q",
        deckNumber: 37,
        img: "static/queen_of_hearts.png",
      },
      kingOfHearts: {
        name: "King of Hearts",
        suit: "hearts",
        color: "red",
        value: "K",
        deckNumber: 38,
        img: "static/king_of_hearts.png",
      },
      aceOfHearts: {
        name: "Ace of Hearts",
        suit: "hearts",
        color: "red",
        value: "A",
        deckNumber: 39,
        img: "static/ace_of_hearts.png",
      },
    },
  ],
  spades: [
    {
      twoOfSpades: {
        name: "Two of Spades",
        suit: "spades",
        color: "black",
        value: "2",
        deckNumber: 40,
        img: "static/2_of_spades.png",
      },
      threeOfSpades: {
        name: "Three of Spades",
        suit: "spades",
        color: "black",
        value: "3",
        deckNumber: 41,
        img: "static/3_of_spades.png",
      },
      fourOfSpades: {
        name: "Four of Spades",
        suit: "spades",
        color: "black",
        value: "4",
        deckNumber: 42,
        img: "static/4_of_spades.png",
      },
      fiveOfSpades: {
        name: "Five of Spades",
        suit: "spades",
        color: "black",
        value: "5",
        deckNumber: 43,
        img: "static/5_of_spades.png",
      },
      sixOfSpades: {
        name: "Six of Spades",
        suit: "spades",
        color: "black",
        value: "6",
        deckNumber: 44,
        img: "static/6_of_spades.png",
      },
      sevenOfSpades: {
        name: "Seven of Spades",
        suit: "spades",
        color: "black",
        value: "7",
        deckNumber: 45,
        img: "static/7_of_spades.png",
      },
      eightOfSpades: {
        name: "Eight of Spades",
        suit: "spades",
        color: "black",
        value: "8",
        deckNumber: 46,
        img: "static/8_of_spades.png",
      },
      nineOfSpades: {
        name: "Nine of Spades",
        suit: "spades",
        color: "black",
        value: "9",
        deckNumber: 47,
        img: "static/9_of_spades.png",
      },
      tenOfSpades: {
        name: "Ten of Spades",
        suit: "spades",
        color: "black",
        value: "10",
        deckNumber: 48,
        img: "static/10_of_spades.png",
      },
      jackOfSpades: {
        name: "Jack of Spades",
        suit: "spades",
        color: "black",
        value: "J",
        deckNumber: 49,
        img: "static/jack_of_spades.png",
      },
      queenOfSpades: {
        name: "Queen of Spades",
        suit: "spades",
        color: "black",
        value: "Q",
        deckNumber: 50,
        img: "static/queen_of_spades.png",
      },
      kingOfSpades: {
        name: "King of Spades",
        suit: "spades",
        color: "black",
        value: "K",
        deckNumber: 51,
        img: "static/king_of_spades.png",
      },
      aceOfSpades: {
        name: "Ace of Spades",
        suit: "spades",
        color: "black",
        value: "A",
        deckNumber: 52,
        img: "static/ace_of_spades.png",
      },
    },
  ],
};

console.log(deck.aceS);
